image: vauxoo/odoo-80-image-shippable-auto
stages:
  - test
  - build
  - upload_image

lint:
  stage: test
  tags:
    - lint
  variables:
    LINT_CHECK: "1"
    TESTS: "0"
  script:
    - source variables.sh
    - sudo apt-get update && sudo apt-get install -y dos2unix
    - git clone --dept=1 https://github.com/vauxoo/maintainer-quality-tools.git -b master ${HOME}/maintainer-quality-tools
    - source "${HOME}/maintainer-quality-tools/travis/travis_gitlab_translate_env"
    - pip3 install deployv-addon-gitlab-tools
    - deployvcmd gitlab_tools check_keys
    - travis_install_nightly
    - travis_run_tests

test:
  stage: test
  tags:
    - odoo
    - test
  coverage: '/^TOTAL.*\s+(\d+\%)$/'
  variables:
    LINT_CHECK: "0"
    TESTS: "1"
  script:
    - source variables.sh
    - pip3 install requests_mock
    - apt-get update && apt-get install -y tree dos2unix
    - git clone --dept=1 https://github.com/vauxoo/maintainer-quality-tools.git -b master ${HOME}/maintainer-quality-tools
    - source "${HOME}/maintainer-quality-tools/travis/travis_gitlab_translate_env"
    - pip3 install deployv-addon-gitlab-tools
    - deployvcmd gitlab_tools check_keys
    - source ${REPO_REQUIREMENTS}/virtualenv/python${TRAVIS_PYTHON_VERSION}/bin/activate
    - travis_install_nightly
    - travis_run_tests
    - travis_after_tests_success || true
    - coverage html --rcfile=${TRAVIS_BUILD_DIR}/.coveragerc -d $CI_COMMIT_REF_SLUG || true
    - coverage report -m --show-missing --rcfile=${TRAVIS_BUILD_DIR}/.coveragerc || true
  artifacts:
    paths:
      - $CI_COMMIT_REF_SLUG

nodemo:
  stage: test
  tags:
    - odoo
    - test
  variables:
    LINT_CHECK: "0"
    TESTS: "1"
    TEST_ENABLE: "0"
    OPTIONS: "--without-demo=all"
    INSTALL_OPTIONS: "--without-demo=all"
  script:
    - source variables.sh
    - pip3 install requests_mock
    - apt-get update && apt-get install -y tree dos2unix
    - git clone --dept=1 https://github.com/vauxoo/maintainer-quality-tools.git -b master ${HOME}/maintainer-quality-tools
    - source "${HOME}/maintainer-quality-tools/travis/travis_gitlab_translate_env"
    - pip3 install deployv-addon-gitlab-tools
    - deployvcmd gitlab_tools check_keys
    - source ${REPO_REQUIREMENTS}/virtualenv/python${TRAVIS_PYTHON_VERSION}/bin/activate
    - travis_install_nightly
    - travis_run_tests
    - travis_after_tests_success || true

build:
  stage: build
  image: quay.io/vauxoo/dockerv:latest
  tags:
    - build
  variables:
    INSTALL: "account_xunnel"
    CUSTOMER: "account_xunnel"
  script:
    - source variables.sh
    - deployvcmd gitlab_tools check_keys
    - deployvcmd gitlab_tools test_images --psql_image='vauxoo/docker-postgresql:9.6-ci' --push_image

bump:
  stage: upload_image
  only:
      - 13.0@vauxoo/xunnel-account
  when: on_success
  tags:
    - odoo
    - test
  script:
    - source variables.sh
    - |
      case "$CI_COMMIT_MESSAGE" in
        *Bump*)
          ;;
        *)
          pip3 install -U deployv-addon-gitlab-tools
          pip install -U bumpversion
          deployvcmd gitlab_tools check_keys
          git config --global user.email "coward@vauxoo.com"
          git config --global user.name "Coward - Auto release"
          git clone -b 13.0 --single-branch git@git.vauxoo.com:vauxoo/xunnel-account.git
          cd xunnel-account
          bumpversion patch
          git push origin 13.0
          ;;
        esac

publish_coverage:
  image: quay.io/vauxoo/dockerv
  stage: build
  allow_failure: true
  dependencies:
    - test
  script:
    - source variables.sh
    - deployvcmd gitlab_tools push_coverage

  environment:
    name: coverage
    url: https://coverage.vauxoo.com/${CI_COMMIT_REF_SLUG}-${CI_PROJECT_NAME}
