export PSQL_VERSION="10"
export VERSION="13.0"
export TRAVIS_PYTHON_VERSION="3.6"
export ODOO_REPO="vauxoo/odoo"
export ODOO_BRANCH="13.0"
export BASE_IMAGE="vauxoo/odoo-130-image"
export MAIN_APP="invoice_xunnel"
export PHANTOMJS_TESTS="0"
